service: time-checker-service

provider:
  deploymentBucket:
    name: deployment-bucket-for-sls
  name: aws
  runtime: python3.9
  region: ap-south-1             # Mumbai region                   

functions:
  timeChecker:
    name: time-checker-lambda
    description: "Lambda function to check if target time has been reached"
    handler: src/handlers/time_checker_lambda/index.lambda_handler
    role: arn:aws:iam::126532164424:role/TestingLambdaRole
    package:
      include:
        - src/handlers/time_checker_lambda/**
      exclude:
        - src/handlers/time_checker_lambda/requirement.txt
        - src/handlers/time_checker_lambda/package/**
    
      

